# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fast_melbo',
                'doc_host': 'https://z3research.github.io',
                'git_url': 'https://github.com/z3research/fast_melbo',
                'lib_path': 'fast_melbo'},
  'syms': {'fast_melbo.core': {'fast_melbo.core.foo': ('core.html#foo', 'fast_melbo/core.py')}}}
